# Generated by Django 4.0.3 on 2023-03-10 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_remove_automobilevo_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='automobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salerecords', to='sales_rest.automobilevo'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salerecords', to='sales_rest.customer'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salerecords', to='sales_rest.salesperson'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='employee_number',
            field=models.CharField(default='unassigned', max_length=100, unique=True),
        ),
    ]
