# Generated by Django 4.0.3 on 2023-03-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_salerecord_price_currency_alter_salerecord_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecord',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
