# Generated by Django 4.0.3 on 2023-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0010_alter_salerecord_automobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
