# Generated by Django 4.0.3 on 2023-03-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_serviceappointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='customer_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='reason',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
